export * from './HomePage'
export * from './AboutPage'
export * from './BlogPage'
export * from './CatalogPage'
export * from './CategoryPage'
export * from './ContactPage'
export * from './SigningPage'